### ISSUE TITLE
Understanding the source

### ISSUE THREAD

**Issue by AbhilashThomas** [JohannesBuchner/k2pdfopt#1]
Hi,

I just downloaded the source and trying to understand how this works. I need to know how are you able to set boundary boxes for the words? Once we have the word coordinates its just rearranging them to fit the screen width. Am I correct?

Could you point me the part of the code which is doing the word detection stuff?

Thanks a lot.

**Comment by JohannesBuchner** [comment]
Hi, this is not my project, I just have a copy here. See http://willus.com/k2pdfopt/
